/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTaskForm: typeof import('./src/components/AddTaskForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TasksList: typeof import('./src/components/TasksList.vue')['default']
  }
}
